import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import "@/styles/globals.css";
import { PageShell } from "@/components/ui/PageShell";
import { SmoothScroll } from "@/components/ui/SmoothScroll";
import { CustomCursor } from "@/components/ui/CustomCursor";

export const metadata: Metadata = {
  title: {
    default: "LMS — AI Marketing & Web Development | Southern California",
    template: "%s | LMS — Southern California",
  },
  description:
    "AI-powered marketing, web development, and automation for businesses in Los Angeles, Inland Empire, Orange County, and San Diego. One operator. Every capability. No ceiling.",
  metadataBase: new URL("https://linearmarketingsolutions.com"),
  openGraph: {
    title: "LMS — AI Marketing & Web Development | Southern California",
    description:
      "AI-powered marketing, web development, and automation for businesses in Los Angeles, Inland Empire, Orange County, and San Diego. One operator. Every capability.",
    url: "https://linearmarketingsolutions.com",
    siteName: "Linear Marketing Solutions",
    locale: "en_US",
    type: "website",
    // OG image auto-generated by app/opengraph-image.tsx (ImageResponse API)
  },
  twitter: {
    card: "summary_large_image",
    title: "LMS — AI Marketing & Web Development | Southern California",
    description:
      "AI-powered marketing, web development, and automation for businesses in Los Angeles, Inland Empire, Orange County, and San Diego.",
  },
  robots: {
    index: true,
    follow: true,
  },
  icons: {
    icon: [
      { url: "/favicon.svg", type: "image/svg+xml" },
    ],
    apple: [
      { url: "/apple-touch-icon.svg", type: "image/svg+xml" },
    ],
  },
  other: {
    "geo.region": "US-CA",
    "geo.placename": "Rancho Cucamonga",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${GeistSans.variable} ${GeistMono.variable}`}
    >
      <head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "ProfessionalService",
              name: "Linear Marketing Solutions",
              alternateName: "LMS",
              url: "https://linearmarketingsolutions.com",
              telephone: "+1-928-302-4852",
              email: "info@linearmarketingsolutions.com",
              description:
                "AI-powered marketing infrastructure, web development, automation, and business operations for growth-stage companies across Southern California.",
              founder: {
                "@type": "Person",
                name: "Blake Pederson",
              },
              areaServed: [
                {
                  "@type": "State",
                  name: "California",
                  containsPlace: [
                    { "@type": "City", name: "Rancho Cucamonga" },
                    { "@type": "City", name: "Los Angeles" },
                    { "@type": "City", name: "San Bernardino" },
                    { "@type": "City", name: "Riverside" },
                    { "@type": "City", name: "Irvine" },
                    { "@type": "City", name: "San Diego" },
                    { "@type": "City", name: "Ontario" },
                    { "@type": "City", name: "Pasadena" },
                    { "@type": "City", name: "Temecula" },
                    { "@type": "City", name: "Anaheim" },
                  ],
                },
              ],
              serviceType: [
                "AI Marketing",
                "Web Development",
                "AI Agent Development",
                "Workflow Automation",
                "SEO",
                "Content Production",
                "CRM Integration",
                "Business Operations",
              ],
              knowsAbout: [
                "Artificial Intelligence",
                "Marketing Automation",
                "Next.js Development",
                "Search Engine Optimization",
                "AI Infrastructure",
              ],
              sameAs: [],
            }),
          }}
        />
      </head>
      <body>
        <SmoothScroll>
          <CustomCursor />
          <PageShell>{children}</PageShell>
        </SmoothScroll>
      </body>
    </html>
  );
}
